# Generated by Django 6.0.3 on 2026-03-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('icona', models.CharField(blank=True, max_length=10, verbose_name='Icona emoji')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200, verbose_name='Nome cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID')),
                ('num_persone', models.IntegerField(default=2, verbose_name='Numero di persone')),
                ('data_ora', models.DateTimeField(verbose_name='Data e ora')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('stato', models.CharField(choices=[('A', 'In attesa di conferma'), ('C', 'Confermata'), ('R', 'Rifiutata'), ('X', 'Annullata')], default='A', max_length=1, verbose_name='Stato')),
                ('creata_il', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('caparra_richiesta', models.BooleanField(default=True, verbose_name='Caparra richiesta')),
                ('caparra_importo', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Importo caparra')),
                ('caparra_pagata', models.BooleanField(default=False, verbose_name='Caparra pagata')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['data_ora'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome sala')),
                ('larghezza', models.IntegerField(default=20, verbose_name='Larghezza griglia')),
                ('altezza', models.IntegerField(default=15, verbose_name='Altezza griglia')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Sale',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('A', 'Aperto'), ('P', 'In preparazione'), ('S', 'Servito'), ('X', 'Pagato')], default='A', max_length=1, verbose_name='Stato')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('aggiornato_il', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('totale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totale')),
                ('sconto_caparra', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sconto caparra')),
                ('cameriere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cameriere')),
                ('prenotazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini', to='ristorante.prenotazione', verbose_name='Prenotazione')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Immagine')),
                ('disponibile', models.BooleanField(default=True, verbose_name='Disponibile')),
                ('allergeni', models.CharField(blank=True, max_length=500, verbose_name='Allergeni')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='ristorante.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='OrdineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=1, verbose_name='Quantità')),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo unitario')),
                ('stato', models.CharField(choices=[('A', 'In attesa'), ('C', 'In cucina'), ('P', 'Pronto'), ('S', 'Servito')], default='A', max_length=1, verbose_name='Stato')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ristorante.ordine', verbose_name='Ordine')),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ristorante.piatto', verbose_name='Piatto')),
            ],
            options={
                'verbose_name': 'Voce ordine',
                'verbose_name_plural': 'Voci ordine',
            },
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero tavolo')),
                ('forma', models.CharField(choices=[('R', 'Rotondo'), ('Q', 'Quadrato'), ('T', 'Rettangolare')], default='Q', max_length=1, verbose_name='Forma')),
                ('capacita', models.IntegerField(default=4, verbose_name='Capacità (posti)')),
                ('stato', models.CharField(choices=[('L', 'Libero'), ('P', 'Prenotato'), ('O', 'Occupato'), ('C', 'Conto richiesto')], default='L', max_length=1, verbose_name='Stato')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Posizione X')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Posizione Y')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tavoli', to='ristorante.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Tavolo',
                'verbose_name_plural': 'Tavoli',
                'ordering': ['numero'],
                'unique_together': {('sala', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='ristorante.tavolo', verbose_name='Tavolo'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='ristorante.tavolo', verbose_name='Tavolo'),
        ),
    ]
