# Generated by Django 6.0.3 on 2026-03-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='svg_altezza',
            field=models.IntegerField(default=800, verbose_name='Altezza canvas SVG (px)'),
        ),
        migrations.AddField(
            model_name='sala',
            name='svg_larghezza',
            field=models.IntegerField(default=1200, verbose_name='Larghezza canvas SVG (px)'),
        ),
        migrations.AddField(
            model_name='sala',
            name='svg_sfondo',
            field=models.FileField(blank=True, null=True, upload_to='sale_svg/', verbose_name='SVG planimetria'),
        ),
        migrations.CreateModel(
            name='TavoloUnione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(blank=True, help_text='Es. "T3+T4" — lascia vuoto per generazione automatica', max_length=50, verbose_name='Etichetta')),
                ('creata_il', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unioni', to='ristorante.sala', verbose_name='Sala')),
                ('tavoli', models.ManyToManyField(related_name='unioni', to='ristorante.tavolo', verbose_name='Tavoli uniti')),
            ],
            options={
                'verbose_name': 'Unione tavoli',
                'verbose_name_plural': 'Unioni tavoli',
            },
        ),
    ]
