# Generated by Django 6.0.3 on 2026-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0002_sala_svg_altezza_sala_svg_larghezza_sala_svg_sfondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piatto',
            name='ingredienti',
            field=models.TextField(blank=True, help_text='Elenco ingredienti e quantità per porzione, usato nella lista spesa cuochi', verbose_name='Ingredienti (per lista spesa)'),
        ),
        migrations.AddField(
            model_name='tavolo',
            name='eprint_email',
            field=models.EmailField(blank=True, help_text='Indirizzo email HP ePrint della stampante associata a questo tavolo', max_length=254, verbose_name='Email ePrint stampante'),
        ),
    ]
