# Generated by Django 6.0.3 on 2026-03-08 17:58

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0003_eprint_ingredienti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniRistorante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='RistoBAR', max_length=200, verbose_name='Nome ristorante')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Slogan')),
                ('indirizzo', models.CharField(blank=True, max_length=200, verbose_name='Indirizzo')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=5, verbose_name='Provincia (sigla)')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('sito', models.URLField(blank=True, verbose_name='Sito web')),
                ('piva', models.CharField(blank=True, max_length=11, verbose_name='Partita IVA')),
                ('cf', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('regime_fiscale', models.CharField(blank=True, default='RF01', max_length=10, verbose_name='Regime fiscale SDI')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('note_scontrino', models.TextField(blank=True, default='Grazie e arrivederci! 🙏', verbose_name='Note piè scontrino')),
                ('note_fattura', models.TextField(blank=True, verbose_name='Note piè fattura')),
            ],
            options={
                'verbose_name': 'Impostazioni Ristorante',
                'verbose_name_plural': 'Impostazioni Ristorante',
            },
        ),
        migrations.AddField(
            model_name='piatto',
            name='aliquota_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Es. 10 per 10% — standard ristorazione; 22 per alcol', max_digits=5, verbose_name='Aliquota IVA %'),
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Scontrino di cortesia'), ('R', 'Ricevuta'), ('F', 'Fattura')], default='S', max_length=1, verbose_name='Tipo')),
                ('numero', models.CharField(blank=True, max_length=30, verbose_name='N° documento')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data emissione')),
                ('cliente_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome / Ragione sociale')),
                ('cliente_indirizzo', models.CharField(blank=True, max_length=300, verbose_name='Indirizzo')),
                ('cliente_cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('cliente_citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('cliente_piva', models.CharField(blank=True, max_length=11, verbose_name='Partita IVA')),
                ('cliente_cf', models.CharField(blank=True, max_length=16, verbose_name='Codice Fiscale')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('cliente_pec', models.EmailField(blank=True, max_length=254, verbose_name='PEC')),
                ('cliente_sdi', models.CharField(blank=True, max_length=10, verbose_name='Codice SDI')),
                ('imponibile', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Imponibile')),
                ('iva_importo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('totale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totale')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('creata_il', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('creata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='ristorante.ordine', verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Documento fiscale',
                'verbose_name_plural': 'Documenti fiscali',
                'ordering': ['-data', '-pk'],
            },
        ),
    ]
