# Generated by Django 6.0.3 on 2026-03-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0004_scontrino_fattura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Sede principale'), ('F', 'Filiale'), ('L', 'Sede legale'), ('A', 'Altro')], default='F', max_length=1, verbose_name='Tipo sede')),
                ('nome', models.CharField(help_text='Es. "Centro storico", "Mare", "Sede legale"', max_length=100, verbose_name='Nome / etichetta')),
                ('indirizzo', models.CharField(max_length=200, verbose_name='Indirizzo')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('provincia', models.CharField(blank=True, max_length=5, verbose_name='Provincia')),
                ('paese', models.CharField(blank=True, default='Italia', max_length=50, verbose_name='Paese')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono diretto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email diretta')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('principale', models.BooleanField(default=False, verbose_name='Usa come indirizzo principale su documenti')),
                ('ristorante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedi', to='ristorante.impostazioniristorante', verbose_name='Ristorante')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedi',
                'ordering': ['-principale', 'nome'],
            },
        ),
    ]
