# Generated by Django 6.0.3 on 2026-03-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0005_sede_indirizzi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('── Recapiti ──', []), ('tel', '📞 Telefono fisso'), ('cel', '📱 Cellulare'), ('eml', '✉️ Email'), ('wap', '💬 WhatsApp'), ('tgm', '✈️ Telegram'), ('fax', '📠 Fax'), ('── Web & Social ──', []), ('web', '🌐 Sito web'), ('fb', '📘 Facebook'), ('ig', '📸 Instagram'), ('tt', '🎵 TikTok'), ('li', '💼 LinkedIn'), ('yt', '▶️ YouTube'), ('── Mappe & Recensioni ──', []), ('gmp', '📍 Google Maps'), ('ta', '⭐ TripAdvisor'), ('tf', '🍴 TheFork'), ('── Delivery ──', []), ('del', '🛵 Deliveroo'), ('glo', '🟡 Glovo'), ('je', '🟠 Just Eat'), ('alt', '📌 Altro')], default='tel', max_length=3, verbose_name='Tipo')),
                ('etichetta', models.CharField(blank=True, help_text='Es. "Prenotazioni", "Chef Marco", "Ufficio amministrativo"', max_length=100, verbose_name='Etichetta')),
                ('valore', models.CharField(help_text='Numero, indirizzo email o URL completo', max_length=500, verbose_name='Valore / URL / Numero')),
                ('principale', models.BooleanField(default=False, verbose_name='Contatto principale per questo tipo')),
                ('pubblico', models.BooleanField(default=True, verbose_name='Mostra sulla vetrina pubblica')),
                ('ordine', models.PositiveSmallIntegerField(default=10, verbose_name='Ordine visualizzazione')),
                ('note', models.TextField(blank=True, verbose_name='Note interne')),
                ('ristorante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='ristorante.impostazioniristorante', verbose_name='Ristorante')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='ristorante.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'ordering': ['ordine', 'tipo'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ristorante__isnull', False), ('sede__isnull', True)), models.Q(('ristorante__isnull', True), ('sede__isnull', False)), _connector='OR'), name='contatto_ha_un_solo_proprietario')],
            },
        ),
    ]
