# Generated by Django 6.0.3 on 2026-03-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0006_contatti'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavolo',
            name='nota',
            field=models.TextField(blank=True, default='', help_text='Nota visibile sul display e-ink (commenti dello chef, suggerimenti, ecc.)', verbose_name='Nota display'),
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome dispositivo')),
                ('tipo', models.CharField(choices=[('ESP32_WIFI', 'ESP32 (WiFi)'), ('ESP32_BLE', 'ESP32 (BLE)'), ('ESP32_MULTI', 'ESP32 (Multi-mode)'), ('ARDUINO_ESP01', 'Arduino + ESP-01'), ('STM32_BLE', 'STM32 (BLE)')], max_length=20, verbose_name='Tipo')),
                ('modalita', models.CharField(choices=[('WIFI', 'WiFi only'), ('BLE', 'Bluetooth only'), ('COMBINED', 'WiFi + BLE')], default='WIFI', max_length=10, verbose_name='Modalità')),
                ('stato', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ERROR', 'Errore'), ('MAINTENANCE', 'Manutenzione')], default='OFFLINE', max_length=15, verbose_name='Stato')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('ble_name', models.CharField(blank=True, max_length=32, verbose_name='Nome BLE')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('server_url', models.CharField(blank=True, max_length=200, verbose_name='URL Server')),
                ('refresh_interval', models.IntegerField(default=60, verbose_name='Interval refresh (sec)')),
                ('piano', models.CharField(blank=True, max_length=20, verbose_name='Piano')),
                ('posizione', models.CharField(blank=True, help_text='Es: "Entrata", "Angolo NW"', max_length=100, verbose_name='Posizione')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo contatto')),
                ('last_status', models.JSONField(blank=True, default=dict, verbose_name='Ultimo stato')),
                ('errori', models.TextField(blank=True, verbose_name='Errori')),
                ('firmware_ver', models.CharField(blank=True, max_length=20, verbose_name='Firmware')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivi', to='ristorante.sala')),
                ('tavolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivo', to='ristorante.tavolo')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivi',
                'ordering': ['sala', 'tavolo', 'nome'],
            },
        ),
    ]
