# Generated by Django 6.0.3 on 2026-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0007_aggiungi_nota_tavolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniristorante',
            name='piatto_del_giorno',
            field=models.CharField(blank=True, help_text='Piatto speciale di oggi, mostrato ai clienti e nella chat AI', max_length=200, verbose_name='Piatto del giorno'),
        ),
    ]
