# Generated by Django 6.0.3 on 2026-03-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0008_aggiungi_piatto_giorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='ble_ping_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ping BLE (ms)'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ble_rssi',
            field=models.IntegerField(blank=True, help_text='Potenza segnale BLE', null=True, verbose_name='RSSI BLE'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='gps_precisione',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precisione GPS (m)'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='latitudine',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitudine'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='longitudine',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitudine'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pos_x_calcolato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posizione X calcolata'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pos_y_calcolato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posizione Y calcolata'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='posizione_precisione',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precisione posizione (m)'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='wifi_ping_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ping WiFi (ms)'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='wifi_rssi',
            field=models.IntegerField(blank=True, help_text='Potenza segnale WiFi', null=True, verbose_name='RSSI WiFi'),
        ),
        migrations.AddField(
            model_name='piatto',
            name='totale_vendite',
            field=models.IntegerField(default=0, help_text='Numero totale di volte che questo piatto è stato ordinato e pagato', verbose_name='Totale vendite'),
        ),
        migrations.CreateModel(
            name='OrdineStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateTimeField(verbose_name='Data ordine')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data pagamento')),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale pagato')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=20, verbose_name='Metodo pagamento')),
                ('nome_cliente', models.CharField(blank=True, max_length=100, verbose_name='Nome cliente')),
                ('note_cliente', models.TextField(blank=True, verbose_name='Note del cliente')),
                ('items_json', models.TextField(help_text='JSON con tutti i piatti ordinati al momento del pagamento', verbose_name='Items ordinati (JSON)')),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storico', to='ristorante.ordine')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ristorante.sala')),
                ('tavolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storico_ordini', to='ristorante.tavolo')),
            ],
            options={
                'verbose_name': 'Ordine Storico',
                'verbose_name_plural': 'Ordini Storici',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
