# Generated by Django 6.0.3 on 2026-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0009_dispositivo_ble_ping_ms_dispositivo_ble_rssi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='codice_destinatario',
            field=models.CharField(blank=True, help_text='Codice SDI o PEC del destinatario', max_length=7, verbose_name='Codice Destinatario'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='data_invio_sdi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data invio SDI'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='fattura_elettronica',
            field=models.BooleanField(default=False, verbose_name='Fattura Elettronica'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='stato_invio',
            field=models.CharField(blank=True, choices=[('BOZZA', 'Bozza'), ('INVIATA', 'Inviata'), ('ACCETTATA', 'Accettata'), ('RIFIUTATA', 'Rifiutata'), ('CONSEGNATA', 'Consegnata')], default='BOZZA', max_length=20, verbose_name='Stato invio'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='xml_contenuto',
            field=models.TextField(blank=True, help_text='Contenuto XML della fattura elettronica (formato FatturaPA)', verbose_name='XML Fattura Elettronica'),
        ),
        migrations.AddField(
            model_name='fattura',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='fatture_xml/', verbose_name='File XML'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram attivo'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='telegram_nome_bot',
            field=models.CharField(blank=True, help_text='Nome del bot es. LaTrattoriaBot', max_length=100, verbose_name='Nome Bot'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='whatsapp_business_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Business ID'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Business attivo'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='whatsapp_nome',
            field=models.CharField(blank=True, help_text='Nome che appare nelle chat', max_length=100, verbose_name='Nome visualizzato'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Numero di telefono business es. +393491234567', max_length=20, verbose_name='Numero WhatsApp'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Phone ID'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=500, verbose_name='WhatsApp Access Token'),
        ),
    ]
