# Generated by Django 6.0.3 on 2026-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0010_fattura_codice_destinatario_fattura_data_invio_sdi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniristorante',
            name='abbonamento_attivo',
            field=models.BooleanField(default=False, verbose_name='Abbonamento attivo'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='abbonamento_fine',
            field=models.DateField(blank=True, null=True, verbose_name='Fine abbonamento'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='abbonamento_inizio',
            field=models.DateField(blank=True, null=True, verbose_name='Inizio abbonamento'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='abbonamento_mensile_euro',
            field=models.DecimalField(decimal_places=2, default=49.9, max_digits=8, verbose_name='Costo mensile (€)'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='dominio',
            field=models.CharField(blank=True, help_text='es. mioristorante.it', max_length=200, verbose_name='Dominio'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='dominio_costo_annuale',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8, verbose_name='Costo dominio annuale (€)'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='dominio_scadenza',
            field=models.DateField(blank=True, null=True, verbose_name='Scadenza dominio'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='note_abbonamento',
            field=models.TextField(blank=True, verbose_name='Note abbonamento'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='social_facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='social_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='social_pinterest',
            field=models.URLField(blank=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='social_tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='social_x',
            field=models.URLField(blank=True, verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='social_youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
