# Generated by Django 6.0.3 on 2026-03-14 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0011_impostazioniristorante_abbonamento_attivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponSconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True, verbose_name='Codice')),
                ('sconto_percentuale', models.IntegerField(default=10, verbose_name='Sconto %')),
                ('sconto_euro', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sconto fisso (€)')),
                ('valore_minimo_ordine', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valore minimo ordine')),
                ('valido_da', models.DateField(blank=True, null=True, verbose_name='Valido da')),
                ('valido_fino', models.DateField(verbose_name='Valido fino')),
                ('utilizzato', models.BooleanField(default=False, verbose_name='Utilizzato')),
                ('utilizzato_il', models.DateTimeField(blank=True, null=True, verbose_name='Utilizzato il')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordine_utilizzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_utilizzato', to='ristorante.ordine')),
            ],
            options={
                'verbose_name': 'Coupon Sconto',
                'verbose_name_plural': 'Coupon Sconti',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='Promemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('tipo', models.CharField(choices=[('ABBONAMENTO', 'Abbonamento RistoBAR'), ('DOMINIO', 'Scadenza dominio'), ('PAGAMENTO', 'Pagamento'), ('MANUTENZIONE', 'Manutenzione'), ('RIUNIONE', 'Riunione'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20, verbose_name='Tipo')),
                ('data_scadenza', models.DateField(verbose_name='Data scadenza')),
                ('completato', models.BooleanField(default=False, verbose_name='Completato')),
                ('data_completato', models.DateTimeField(blank=True, null=True, verbose_name='Data completamento')),
                ('ricorrente', models.BooleanField(default=False, verbose_name='Ricorrente')),
                ('frequenza_ricorrenza', models.CharField(choices=[('NESSUNA', 'Nessuna'), ('SETTIMANALE', 'Settimanale'), ('MENSILE', 'Mensile'), ('BIMESTRALE', 'Bimestrale'), ('SEMESTRALE', 'Semestrale'), ('ANNUALE', 'Annuale')], default='NESSUNA', max_length=20, verbose_name='Frequenza')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promemoria_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promemoria',
                'verbose_name_plural': 'Promemoria',
                'ordering': ['-data_scadenza'],
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina'), ('ALTRO', 'Altro'), ('NSA', 'Preferisco non dire')], max_length=10, verbose_name='Sesso')),
                ('eta', models.IntegerField(blank=True, null=True, verbose_name='Età')),
                ('valutazione_cibo', models.IntegerField(default=0, verbose_name='Valutazione cibo')),
                ('valutazione_servizio', models.IntegerField(default=0, verbose_name='Valutazione servizio')),
                ('valutazione_ambiente', models.IntegerField(default=0, verbose_name='Valutazione ambiente')),
                ('valutazione_prezzo', models.IntegerField(default=0, verbose_name='Valutazione rapporto qualità/prezzo')),
                ('risposta_aperte', models.JSONField(blank=True, default=list, verbose_name='Risposte aperte')),
                ('commenti', models.TextField(blank=True, verbose_name='Commenti')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ristorante.couponsconto')),
                ('prenotazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionari', to='ristorante.prenotazione')),
                ('tavolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ristorante.tavolo')),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionari',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='ReportPeriodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SETTIMANALE', 'Settimanale'), ('MENSILE', 'Mensile'), ('BIMESTRALE', 'Bimestrale'), ('SEMESTRALE', 'Semestrale'), ('ANNUALE', 'Annuale')], max_length=20, verbose_name='Tipo report')),
                ('data_inizio', models.DateField(verbose_name='Data inizio periodo')),
                ('data_fine', models.DateField(verbose_name='Data fine periodo')),
                ('totale_incassi', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totale incassi')),
                ('totale_ordini', models.IntegerField(default=0, verbose_name='Totale ordini')),
                ('totale_prenotazioni', models.IntegerField(default=0, verbose_name='Totale prenotazioni')),
                ('tasso_prenotazioni_confermate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasso conferme %')),
                ('piatti_piu_venduti', models.JSONField(blank=True, default=list, verbose_name='Piatti più venduti')),
                ('analisi_ai', models.TextField(blank=True, verbose_name='Analisi AI')),
                ('suggerimenti_miglioramento', models.TextField(blank=True, verbose_name='Suggerimenti')),
                ('costo_abbonamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo abbonamento')),
                ('costo_dominio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo dominio')),
                ('margine_netto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Margine netto')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Periodico',
                'verbose_name_plural': 'Report Periodici',
                'ordering': ['-data_fine'],
            },
        ),
    ]
