# Generated by Django 6.0.3 on 2026-03-14 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0012_couponsconto_promemoria_questionario_reportperiodico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdottoMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome prodotto')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Barcode')),
                ('fornitore', models.CharField(blank=True, max_length=200, verbose_name='Fornitore')),
                ('quantita', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantità')),
                ('unita_misura', models.CharField(choices=[('KG', 'Kg'), ('LT', 'Litri'), ('PZ', 'Pezzi'), ('BL', 'Buste'), ('BT', 'Bottiglie'), ('CS', 'Cassette')], default='PZ', max_length=5, verbose_name='Unità misura')),
                ('data_arrivo', models.DateField(default=datetime.date.today, verbose_name='Data arrivo')),
                ('data_scadenza', models.DateField(blank=True, null=True, verbose_name='Data scadenza')),
                ('data_apertura', models.DateField(blank=True, null=True, verbose_name='Data apertura')),
                ('giorni_dopo_apertura', models.IntegerField(default=7, verbose_name='Giorni validi dopo apertura')),
                ('stato', models.CharField(choices=[('DISPONIBILE', 'Disponibile'), ('APERTO', 'Aperto'), ('SCADUTO', 'Scaduto'), ('IN_USO', 'In uso'), ('ESAURITO', 'Esaurito')], default='DISPONIBILE', max_length=15, verbose_name='Stato')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prodotto Magazzino',
                'verbose_name_plural': 'Prodotti Magazzino',
                'ordering': ['data_scadenza', 'nome'],
            },
        ),
    ]
