# Generated by Django 6.0.3 on 2026-03-14 15:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0013_prodottomagazzino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CiboRimasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('quantita', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Quantità rimasta')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ristorante.piatto')),
            ],
            options={
                'verbose_name': 'Cibo Rimasto',
                'verbose_name_plural': 'Cibi Rimasti',
                'ordering': ['-data', '-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='ListaSpesaGenerata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_generazione', models.DateField(default=datetime.date.today, verbose_name='Data generazione')),
                ('data_riferimento', models.DateField(help_text='Per quale giorno è la lista', verbose_name='Data riferimento')),
                ('prodotti_json', models.JSONField(default=list, verbose_name='Prodotti necessari')),
                ('cibi_rimasti_json', models.JSONField(default=list, verbose_name='Cibi rimasti')),
                ('prodotti_consumati_json', models.JSONField(default=list, verbose_name='Prodotti consumati')),
                ('totale_stimato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totale stimato')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('generata_il', models.DateTimeField(auto_now_add=True)),
                ('generata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista Spesa Generata',
                'verbose_name_plural': 'Liste Spesa Generate',
                'ordering': ['-data_generazione'],
            },
        ),
    ]
