# Generated by Django 6.0.3 on 2026-03-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0014_ciborimasto_listaspesagenerata'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniristorante',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID chat o gruppo dove inviare le notifiche (es. -1003760305730)', max_length=50, verbose_name='Telegram Chat ID notifiche'),
        ),
    ]
