# Generated by Django 6.0.3 on 2026-03-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0015_impostazioniristorante_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniristorante',
            name='orari',
            field=models.TextField(blank=True, help_text='Es. Lun-Ven 12:00-15:00 / 19:00-23:00 · Sab-Dom 12:00-23:00', verbose_name='Orari di apertura'),
        ),
    ]
