# Generated by Django 6.0.3 on 2026-03-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0016_impostazioniristorante_orari'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniristorante',
            name='mostra_lavora_con_noi',
            field=models.BooleanField(default=False, help_text='Abilita la sezione candidature nel footer della vetrina pubblica', verbose_name='Mostra sezione "Lavora con noi"'),
        ),
    ]
