# Generated by Django 6.0.3 on 2026-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0017_mostra_lavora_con_noi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='citta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='sala',
            name='descrizione',
            field=models.TextField(blank=True, help_text='Note visibili nella pianta (es. "Vista sul mare", "No animali")', verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='sala',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='sala',
            name='nazione',
            field=models.CharField(blank=True, default='Italia', max_length=100, verbose_name='Nazione'),
        ),
        migrations.AddField(
            model_name='sala',
            name='piano',
            field=models.IntegerField(blank=True, help_text='0=Piano Terra, 1=Primo Piano, -1=Seminterrato…', null=True, verbose_name='Piano'),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo_locale',
            field=models.CharField(blank=True, choices=[('PT', 'Piano Terra'), ('P1', 'Primo Piano'), ('P2', 'Secondo Piano'), ('SI', 'Seminterrato / Cantina'), ('TR', 'Terrazza / Rooftop'), ('GI', 'Giardino / Cortile'), ('SP', 'Sala Privata / VIP'), ('BA', 'Area Bancone / Bar'), ('ES', 'Area Esterna'), ('AL', 'Altro')], default='PT', max_length=2, verbose_name='Tipo area'),
        ),
    ]
