# Generated by Django 6.0.3 on 2026-03-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0018_sala_pianta_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioniristorante',
            name='ddt_abilitato',
            field=models.BooleanField(default=False, help_text='Abilita la generazione di DDT per le consegne a domicilio', verbose_name='DDT abilitato'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='ddt_aspetto',
            field=models.CharField(blank=True, default='Confezione', help_text='Come si presentano i colli (es. Confezione, Borsa termica, Scatola)', max_length=100, verbose_name='Aspetto esteriore beni'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='ddt_causale',
            field=models.CharField(blank=True, default='Vendita', help_text='Motivo del trasporto (es. Vendita, Conto lavoro, Reso)', max_length=200, verbose_name='Causale predefinita'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='ddt_note',
            field=models.TextField(blank=True, help_text='Note aggiuntive stampate sul DDT (istruzioni di consegna, temperature, ecc.)', verbose_name='Note DDT'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='ddt_porto',
            field=models.CharField(blank=True, choices=[('F', 'Franco (a carico del mittente)'), ('A', 'Assegnato (a carico del destinatario)')], default='F', max_length=1, verbose_name='Porto'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='ddt_vettore',
            field=models.CharField(blank=True, help_text='Nome o ragione sociale del corriere / rider (es. Glovo, corriere interno)', max_length=200, verbose_name='Vettore'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='pag_dip_giorno',
            field=models.IntegerField(blank=True, default=27, help_text='Giorno del mese in cui vengono pagati gli stipendi (es. 27)', null=True, verbose_name='Giorno di pagamento'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='pag_dip_iban',
            field=models.CharField(blank=True, help_text="IBAN da cui vengono accreditati gli stipendi (può differire dall'IBAN principale)", max_length=34, verbose_name='IBAN conto stipendi'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='pag_dip_metodo',
            field=models.CharField(blank=True, choices=[('B', 'Bonifico bancario'), ('C', 'Contanti'), ('A', 'Assegno'), ('P', 'Payroll provider esterno')], default='B', max_length=1, verbose_name='Metodo pagamento stipendi'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='pag_dip_note',
            field=models.TextField(blank=True, help_text='Istruzioni interne, riferimenti sindacali, contratto collettivo applicato', verbose_name='Note pagamenti dipendenti'),
        ),
        migrations.AddField(
            model_name='impostazioniristorante',
            name='pag_dip_provider',
            field=models.CharField(blank=True, help_text='Nome del provider di buste paga (es. Zucchetti, Paghe Web, consulente)', max_length=200, verbose_name='Payroll provider'),
        ),
    ]
