# Generated by Django 6.0.3 on 2026-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ristorante', '0019_pagamenti_dip_ddt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavolo',
            name='etichetta',
            field=models.CharField(blank=True, default='', help_text='Nome visualizzato nell\'editor per eventi/matrimoni (es. "Famiglia Rossi")', max_length=100, verbose_name='Etichetta evento'),
        ),
    ]
